# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_p1_p2_mle_cpp <- function(omega) {
    .Call(`_gmwmx2_estimate_p1_p2_mle_cpp`, omega)
}

create_vec_theo_autocov_omega_cpp <- function(p1, p2, n) {
    .Call(`_gmwmx2_create_vec_theo_autocov_omega_cpp`, p1, p2, n)
}

compute_h_cpp <- function(kappa, N) {
    .Call(`_gmwmx2_compute_h_cpp`, kappa, N)
}

vec_mean_autocov_powerlaw <- function(kappa, N) {
    .Call(`_gmwmx2_vec_mean_autocov_powerlaw`, kappa, N)
}

var_cov_powerlaw_cpp <- function(sigma2, kappa, n) {
    .Call(`_gmwmx2_var_cov_powerlaw_cpp`, sigma2, kappa, n)
}

compute_power_of_a_base <- function(x, J) {
    .Call(`_gmwmx2_compute_power_of_a_base`, x, J)
}

autocovariance_to_wv <- function(acf, tau) {
    .Call(`_gmwmx2_autocovariance_to_wv`, acf, tau)
}

compute_cov_W_scale_1_cpp <- function(Sigma_X) {
    .Call(`_gmwmx2_compute_cov_W_scale_1_cpp`, Sigma_X)
}

compute_cov_W_all_scales_cpp <- function(Sigma_X) {
    .Call(`_gmwmx2_compute_cov_W_all_scales_cpp`, Sigma_X)
}

compute_index_pairs_scales_cpp <- function(max_j) {
    .Call(`_gmwmx2_compute_index_pairs_scales_cpp`, max_j)
}

compute_cov_W_between_scales_all_scales_cpp <- function(mat_index, n, lst_cov_W) {
    .Call(`_gmwmx2_compute_cov_W_between_scales_all_scales_cpp`, mat_index, n, lst_cov_W)
}

f_jk_cpp <- function(h, cov_Wj_Wjk, Mjk, Mj) {
    .Call(`_gmwmx2_f_jk_cpp`, h, cov_Wj_Wjk, Mjk, Mj)
}

f_jk_approx_cpp <- function(h, cov_Wj_Wjk, Mjk, Mj, approx_type = "3") {
    .Call(`_gmwmx2_f_jk_approx_cpp`, h, cov_Wj_Wjk, Mjk, Mj, approx_type)
}

compute_cov_wv_cpp_1 <- function(cov_W_j, J, n, mat_index) {
    .Call(`_gmwmx2_compute_cov_wv_cpp_1`, cov_W_j, J, n, mat_index)
}

compute_cov_wv_cpp <- function(Sigma_X) {
    .Call(`_gmwmx2_compute_cov_wv_cpp`, Sigma_X)
}

test_power <- function(j) {
    .Call(`_gmwmx2_test_power`, j)
}

compute_l_index_to_compute_cpp <- function(Mjk, approx_type) {
    .Call(`_gmwmx2_compute_l_index_to_compute_cpp`, Mjk, approx_type)
}

compute_indices <- function(all_l_values, lst_index_row) {
    .Call(`_gmwmx2_compute_indices`, all_l_values, lst_index_row)
}

compute_cov_wv_cpp_approx_faster <- function(Sigma_X, approx_type = "1") {
    .Call(`_gmwmx2_compute_cov_wv_cpp_approx_faster`, Sigma_X, approx_type)
}

sum_all_upper_diagonals <- function(matrix) {
    .Call(`_gmwmx2_sum_all_upper_diagonals`, matrix)
}

linear_interp_cpp <- function(x, y, xout) {
    .Call(`_gmwmx2_linear_interp_cpp`, x, y, xout)
}

pre_compute_quantities_on_D_only_required_smarter_cpp <- function(D, approx_type = "3") {
    .Call(`_gmwmx2_pre_compute_quantities_on_D_only_required_smarter_cpp`, D, approx_type)
}

compute_all_mean_diag_fast_w_linear_interp_only_required_cpp <- function(mat_D_q_term_1, mat_D_q_term_2, sum_on_sub_diag_of_D, vec_autocov, approx_type = "3") {
    .Call(`_gmwmx2_compute_all_mean_diag_fast_w_linear_interp_only_required_cpp`, mat_D_q_term_1, mat_D_q_term_2, sum_on_sub_diag_of_D, vec_autocov, approx_type)
}

