# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gen_flicker <- function(N, sigma) {
    .Call(`_gmwmx2_gen_flicker`, N, sigma)
}

create_var_cov_flicker <- function(sigma_pl, N) {
    .Call(`_gmwmx2_create_var_cov_flicker`, sigma_pl, N)
}

create_U_flicker <- function(N) {
    .Call(`_gmwmx2_create_U_flicker`, N)
}

mean_all_diagonals <- function(matrix) {
    .Call(`_gmwmx2_mean_all_diagonals`, matrix)
}

mean_all_upper_diagonals <- function(matrix) {
    .Call(`_gmwmx2_mean_all_upper_diagonals`, matrix)
}

compute_h_cpp <- function(kappa, N) {
    .Call(`_gmwmx2_compute_h_cpp`, kappa, N)
}

return_cumsum_product_of_shifted_vector_cpp <- function(vec_x, shift) {
    .Call(`_gmwmx2_return_cumsum_product_of_shifted_vector_cpp`, vec_x, shift)
}

vec_mean_autocov_per_diag_cpp <- function(kappa, N) {
    .Call(`_gmwmx2_vec_mean_autocov_per_diag_cpp`, kappa, N)
}

vec_mean_autocov_per_diag_2_cpp <- function(kappa, N) {
    .Call(`_gmwmx2_vec_mean_autocov_per_diag_2_cpp`, kappa, N)
}

var_cov_powerlaw_cpp <- function(sigma2, kappa, n) {
    .Call(`_gmwmx2_var_cov_powerlaw_cpp`, sigma2, kappa, n)
}

wn_autocovariance <- function(sigma2_wn, n) {
    .Call(`_gmwmx2_wn_autocovariance`, sigma2_wn, n)
}

fast_toeplitz_matrix_from_vector_cpp <- function(v) {
    .Call(`_gmwmx2_fast_toeplitz_matrix_from_vector_cpp`, v)
}

compute_power_of_a_base <- function(x, J) {
    .Call(`_gmwmx2_compute_power_of_a_base`, x, J)
}

autocovariance_to_wv <- function(acf, tau) {
    .Call(`_gmwmx2_autocovariance_to_wv`, acf, tau)
}

get_mean_per_diag_I_minus_H_Sigma_cpp_4 <- function(mat_I_minus_H, mat_Sigma) {
    .Call(`_gmwmx2_get_mean_per_diag_I_minus_H_Sigma_cpp_4`, mat_I_minus_H, mat_Sigma)
}

objective_function_wn_flicker_eps_hat_cpp <- function(theta, scales, wv_var, wv_ci_up, wv_ci_low, n, Q_matrix) {
    .Call(`_gmwmx2_objective_function_wn_flicker_eps_hat_cpp`, theta, scales, wv_var, wv_ci_up, wv_ci_low, n, Q_matrix)
}

objective_function_wn_flicker_eps_hat_cpp_2 <- function(theta, scales, wv_var, wv_ci_up, wv_ci_low, n, Q_matrix) {
    .Call(`_gmwmx2_objective_function_wn_flicker_eps_hat_cpp_2`, theta, scales, wv_var, wv_ci_up, wv_ci_low, n, Q_matrix)
}

